[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"



# 1.
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# 2.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200